stages:
  prepare:
    cmd: python mlops_equipo_63/prepare.py data/raw/online_news_modified.csv 
      data/processed/online_news_clean.csv
    deps:
    - data/raw/online_news_modified.csv
    - mlops_equipo_63/prepare.py
    outs:
    - data/processed/online_news_clean.csv
