# Configuración global del proyecto
project:
  name: popularity_prediction
  random_state: 12

# Parámetros de preprocesamiento
preprocessing:
  imputation_strategy: median
  test_size: 0.2
  random_state: 12
  target_threshold: null  # null = usar mediana

# Parámetros de entrenamiento
training:
  n_trials: 60
  cv_folds: 4
  random_state: 12
  
# Configuración MLflow
mlflow:
  tracking_uri: file:./mlruns
  experiment_name: News_Popularity_Pipeline
  
# Configuración DVC
dvc:
  remote: s3remote